version: '3'

services:
  nginx:
    build:
      context: docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./www:/var/www
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: "Dockerfile-${PHP_VERSION}"
      args:
        - MAGENTO_VERSION=${MAGENTO_VERSION}
    volumes:
      - ./www:/var/www
    expose:
      - ${PHP_UPSTREAM_PORT}

  mariadb:
    image: mariadb:10
    volumes:
      - ${APP_DIR}/docker/temp/mariadb:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=root
